-- ACTUALIZACIÓN PARA EL MÓDULO DE NOTICIAS (GALERÍA Y REDES SOCIALES)
-- Ejecuta esto en la pestaña SQL de phpMyAdmin en Hostinger

ALTER TABLE news ADD COLUMN IF NOT EXISTS gallery LONGTEXT DEFAULT NULL;
ALTER TABLE news ADD COLUMN IF NOT EXISTS show_social TINYINT DEFAULT 1;
